# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_cityseerr_wrappers", use_symbols = TRUE, package_name = "cityseerr")

#' @usage NULL
#' @useDynLib cityseerr, .registration = TRUE
NULL

init_network <- function(nodes, edges) .Call(wrap__init_network, nodes, edges)

compute_centrality_ <- function(network, distances, betas, type) .Call(wrap__compute_centrality_, network, distances, betas, type)

network_info_helper <- function(x) .Call(wrap__network_info_helper, x)

centrality_info_helper <- function(x) .Call(wrap__centrality_info_helper, x)


# nolint end
